- name: Create kioskReactor dir if not exists
  ansible.builtin.command: mkdir -p /home/{{ user }}/kioskReactor

- name: get files in kioskReactor folder
  command: ls /home/{{ user }}/kioskReactor/
  register: files_in_kioskReactor

- name: get files in home folder
  command: ls -a /home/{{ user }}/
  register: files_in_homeFolder

- name: Copy script files killSystem.sh
  ansible.builtin.command: cp killSystem.sh /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('killSystem.sh') == -1
  
- name: make killSystem.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystem.sh  
    state: touch
    mode: u+x,g+x,o+x

- name: Copy script files launchSystem.sh
  ansible.builtin.command: cp launchSystemLite.sh /home/{{ user }}/kioskReactor/launchSystem.sh
  when: files_in_kioskReactor.stdout.find('launchSystem.sh') == -1
  
- name: make launchSystem.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/launchSystem.sh  
    state: touch
    mode: u+x,g+x,o+x
  
- name: Copy script files killSystemNoChrome.sh
  ansible.builtin.command: cp killSystemNoChrome.sh /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('killSystemNoChrome.sh') == -1

- name: make killSystemNoChrome.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystemNoChrome.sh
    state: touch
    mode: u+x,g+x,o+x

- name: make killChrome.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killChrome.sh
    state: touch
    mode: u+x,g+x,o+x

- name: rsync programs file
  ansible.builtin.command: rsync -avz ./programs /home/{{ user }}/kioskReactor

- name: rsync conf file
  ansible.builtin.command: rsync --ignore-existing -avz ./conf /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('conf') == -1

- name: change owner  
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/kioskReactor

- name: change owner auto start
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/.config

- name: install node.js package.
  community.general.npm:
    path: /home/{{ user }}/kioskReactor/programs/jsScripts

- name: install rc.local
  ansible.builtin.command: cp ./rc.local /etc/rc.local