- name: Create kioskReactor dir if not exists
  ansible.builtin.command: mkdir -p /home/{{ user }}/kioskReactor

- name: Copy script files killSystem.sh
  ansible.builtin.command: cp killSystem.sh /home/{{ user }}/kioskReactor
  
- name: make killSystem.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystem.sh  
    state: touch
    mode: u+x,g+x,o+x

- name: Copy script files launchSystem.sh
  ansible.builtin.command: cp launchSystem.sh /home/{{ user }}/kioskReactor
  
- name: make launchSystem.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/launchSystem.sh  
    state: touch
    mode: u+x,g+x,o+x
  
- name: Copy script files killSystemNoChrome.sh
  ansible.builtin.command: cp killSystemNoChrome.sh /home/{{ user }}/kioskReactor

- name: make killSystemNoChrome.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystemNoChrome.sh
    state: touch
    mode: u+x,g+x,o+x
    
- name: Copy script files killSystemNoChrome.sh
  ansible.builtin.command: cp killSystemNoChrome.sh /home/{{ user }}/kioskReactor

- name: Copy open box autostart
  ansible.builtin.command: cp openbox/autostart /etc/xdg/openbox/

- name: create local autostart openbox
  ansible.builtin.command: mkdir -p /home/{{ user }}/.config/openbox

- name: copy autostart local script
  ansible.builtin.command: cp openbox/autostartlocal /home/{{ user }}/.config/openbox/autostart

- name: copy startOpenBox local script
  ansible.builtin.command: cp openbox/startOpenBox.sh /home/{{ user }}/kioskReactor

- name: make killChrome.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killChrome.sh
    state: touch
    mode: u+x,g+x,o+x

- name: rsync programs file
  ansible.builtin.command: rsync -avz ./programs /home/{{ user }}/kioskReactor

- name: Ansible conf check directory.
  ansible.builtin.slurp:
    src: /home/{{ user }}/kioskReactor/conf
  register: confFolder

- name: rsync conf file
  ansible.builtin.command: rsync --ignore-existing -avz ./conf /home/{{ user }}/kioskReactor
  when: confFolder.stat.isdir is not defined

- name: change owner  
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/kioskReactor

- name: change owner auto start
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/.config

- name: make startOpenBox.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/startOpenBox.sh
    state: touch
    mode: u+x,g+x,o+x

- name: install node.js package.
  community.general.npm:
    path: /home/{{ user }}/kioskReactor/programs/jsScripts