- name: Create kioskReactor dir if not exists
  ansible.builtin.command: mkdir -p /home/{{ user }}/kioskReactor

- name: get files in kioskReactor folder
  command: ls /home/{{ user }}/kioskReactor/
  register: files_in_kioskReactor

- name: get files in home folder
  command: ls -a /home/{{ user }}/
  register: files_in_homeFolder

- name: Copy script files killSystem.sh
  ansible.builtin.command: cp killSystem.sh /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('killSystem.sh') == -1
  
- name: make killSystem.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystem.sh  
    state: touch
    mode: u+x,g+x,o+x

- name: Copy script files launchSystem.sh
  ansible.builtin.command: cp launchSystem.sh /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('launchSystem.sh') == -1
  
- name: make launchSystem.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/launchSystem.sh  
    state: touch
    mode: u+x,g+x,o+x
  
- name: Copy script files killSystemNoChrome.sh
  ansible.builtin.command: cp killSystemNoChrome.sh /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('killSystemNoChrome.sh') == -1

- name: make killSystemNoChrome.sh executable 
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killSystemNoChrome.sh
    state: touch
    mode: u+x,g+x,o+x

- name: Copy open box autostart
  ansible.builtin.command: cp openbox/autostart /etc/xdg/openbox/

- name: create local autostart openbox
  ansible.builtin.command: mkdir -p /home/{{ user }}/.config/openbox

- name: copy autostart local script
  ansible.builtin.command: cp openbox/autostartlocal /home/{{ user }}/.config/openbox/autostart

- name: copy startOpenBox local script
  ansible.builtin.command: cp openbox/startOpenBox.sh /home/{{ user }}/kioskReactor

- name: make killChrome.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/killChrome.sh
    state: touch
    mode: u+x,g+x,o+x

- name: rsync programs file
  ansible.builtin.command: rsync -avz ./programs /home/{{ user }}/kioskReactor

- name: rsync conf file
  ansible.builtin.command: rsync --ignore-existing -avz ./conf /home/{{ user }}/kioskReactor
  when: files_in_kioskReactor.stdout.find('conf') == -1

- name: change owner  
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/kioskReactor

- name: change owner auto start
  ansible.builtin.command: sudo chown -R {{ user }}:{{ user }} /home/{{ user }}/.config

- name: make startOpenBox.sh executable
  ansible.builtin.file:
    path: /home/{{ user }}/kioskReactor/startOpenBox.sh
    state: touch
    mode: u+x,g+x,o+x

- name: install node.js package.
  community.general.npm:
    path: /home/{{ user }}/kioskReactor/programs/jsScripts

- name: add .bash_profile to start X in console mode
  ansible.builtin.command: cp bash/.bash_profile /home/{{ user }}
  when: files_in_homeFolder.stdout.find('.bash_profile') == -1

- name: change .bash_profile owner
  ansible.builtin.command: sudo chown {{ user }}:{{ user }} /home/{{ user }}/.bash_profile
  when: files_in_homeFolder.stdout.find('.bash_profile') == -1

- name: add .xinitrc to start X with open box
  ansible.builtin.command: cp xinit/.xinitrc /home/{{ user }}
  when: files_in_homeFolder.stdout.find('.xinitrc') == -1

- name: change .xinitrc owner
  ansible.builtin.command: sudo chown {{ user }}:{{ user }} /home/{{ user }}/.xinitrc
  when: files_in_homeFolder.stdout.find('.xinitrc') == -1