---
- hosts: localhost
  pre_tasks:
    - name: upade repository
      apt:
        update_cache: yes
    
  
  tasks:
    - include: ansibleTasks/node.yml
    - include: ansibleTasksLite/packages.yml
    - include: ansibleTasksLite/syncTotemFiles.yml