---
- hosts: localhost

  tasks:
    - name: Create kioskReactor dir if not exists
      command: "mkdir -p /cygdrive/c/kioskReactor"

    - name: get files in kioskReactor folder
      command: "ls /cygdrive/c/kioskReactor"
      register: files_in_kioskReactor

    - name: Copy script file launchSystemWin.sh
      command: "cp launchSystemWin.sh /cygdrive/c/kioskReactor"

    - name: Copy script file kill.bat
      command: "cp kill.bat /cygdrive/c/kioskReactor"

    - name: Copy script file update.bat
      command: "cp update.bat /cygdrive/c/kioskReactor"

    - name: Copy script file update.sh
      command: "cp update.sh /cygdrive/c/kioskReactor"

    - name: Copy ngrok
      command: "cp winutil/ngrok.exe /cygdrive/c/kioskReactor"
      ignore_errors: yes

    - name: Copy script file killSystemWin.sh
      command: "cp killSystemWin.sh /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('killSystemWin.sh') == -1
      ignore_errors: yes

    - name: Copy script file update.sh
      command: "cp update.sh /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('update.sh') == -1
      ignore_errors: yes

    - name: Copy script file launchSystemWinWithCPSReader.sh
      command: "cp launchSystemWinWithCPSReader.sh /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('launchSystemWinWithCPSReader.sh') == -1
      ignore_errors: yes

    - name: Copy script file launchWithCps.bat
      command: "cp launchWithCps.bath /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('launchWithCps.bat') == -1
      ignore_errors: yes

    - name: Copy script file installNPM.bat
      command: "cp installNPM.bat /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('installNPM.bat') == -1
      ignore_errors: yes

    - name: rsync scriptUtil
      command: "rsync -avz ./scriptUtil /cygdrive/c/kioskReactor"

    - name: rsync programs file
      command: "rsync -avz ./programs /cygdrive/c/kioskReactor"

    - name: Create kioskReactor conf dir if not exists
      command: "mkdir -p /cygdrive/c/kioskReactor/conf"

    - name: rsync conf file
      command: "rsync --ignore-existing -avz ./confWin/ /cygdrive/c/kioskReactor/conf/"
      when: files_in_kioskReactor.stdout.find('conf') == -1
