---
- hosts: localhost
  pre_tasks:
    - name: update repository
      apt:
        update_cache: yes
    
  
  tasks:
    - include: ansibleTasks/node.yml
    - include: ansibleTasks/packages.yml
    - include: ansibleTasks/syncTotemFiles.yml