---
- hosts: localhost

  tasks:
    - name: Create kioskReactor dir if not exists
      command: "mkdir -p /cygdrive/c/kioskReactor"

    - name: get files in kioskReactor folder
      command: "ls /cygdrive/c/kioskReactor"
      register: files_in_kioskReactor

    - name: Copy script file launchSystem.ps1
      command: "cp launchSystem.ps1 /cygdrive/c/kioskReactor"
      when: files_in_kioskReactor.stdout.find('launchSystem.ps1') == -1

    - name: rsync programs file
      command: "rsync -avz ./programs /cygdrive/c/kioskReactor"

    - name: Create kioskReactor conf dir if not exists
      command: "mkdir -p /cygdrive/c/kioskReactor/conf"

    - name: rsync conf file
      command: "rsync --ignore-existing -avz ./confWin/ /cygdrive/c/kioskReactor/conf/"
      when: files_in_kioskReactor.stdout.find('conf') == -1

    - name: install node.js package.
      community.general.npm:
        path: "/cygdrive/c/kioskReactor/programs/jsScripts"
